config/routes.rb
SampleApp::Application.routes.draw do

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]  
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '*unmatched_route', :to => 'static_pages#nil_routes'

  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  # i18n multilanguage.
  before_action :set_locale
  # Mobile
  before_filter :prepare_for_mobile
  # Mobile

  def set_locale
    #I18n.locale = params[:locale] || I18n.default_locale
    if params[:locale]
      # Language switcher
      I18n.locale = params[:locale] || I18n.default_locale
    else
      I18n.locale = (http_accept_language.compatible_language_from(I18n.available_locales)) || (I18n.default_locale)
    end
  end

  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  # Resque form for invalid authentificitytoken
  rescue_from ActionController::InvalidAuthenticityToken, :with => :bad_token
  def bad_token
    flash[:warning] = 'Your session has expired.'
    redirect_to signin_path
  end
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  def record_not_found
    redirect_to root_path
  end
  rescue_from I18n::InvalidLocale, :with => :invalid_locale
  def invalid_locale
    I18n.locale = I18n.default_locale
    redirect_to root_path
  end

# Mobile
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :html if mobile_device?
  end
# Mobile

  # remember user language choise in navigation process
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    {locale: I18n.locale}
  end

  ###########################BOOTSTRAP ELEMENTS FOR ALL###########################
  require 'action_view/helpers/tags/base'
  # Most input types need the form-control class on them.  This is the easiest way to get that into every form input
  module BootstrapTag
    FORM_CONTROL_CLASS = 'form-control'

    def tag(name, options, *)
      options = add_bootstrap_class_to_options options, true if name.to_s == 'input'
      super
    end

    private

    def content_tag_string(name, content, options, *)
      options = add_bootstrap_class_to_options options if name.to_s.in? %w(select textarea)
      super
    end

    def add_bootstrap_class_to_options(options, check_type = false)
      options = {} if options.nil?
      options.stringify_keys!
      if !check_type || options['type'].to_s.in?(%w(text password number email))
        options['class'] = [] unless options.has_key? 'class'
        options['class'] << FORM_CONTROL_CLASS if options['class'].is_a?(Array) && !options['class'].include?(FORM_CONTROL_CLASS)
        options['class'] << " #{FORM_CONTROL_CLASS}" if options['class'].is_a?(String) && options['class'] !~ /\b#{FORM_CONTROL_CLASS}\b/
      end
      options
    end
  end

  ActionView::Helpers::Tags::Base.send :include, BootstrapTag
  ActionView::Base.send :include, BootstrapTag
  ###########################BOOTSTRAP ELEMENTS FOR ALL###########################

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
    @static_pages = [root_url, privacy_and_security_url, terms_of_use_url]
    @users = User.all
    @blogs = Blog.all
    @partners = Partner.all
    respond_to do |format|
      format.xml
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
    end
  end

  def nil_routes
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the our website!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "UANZ"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_admin.html.erb
</br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= (t 'admin.admin_management') %></h3>
        </div>
        <div class="panel-body">
          <%= link_to (t 'admin.users'), users_path, class: "btn btn-sm btn-primary" %> |
          <%= link_to (t 'admin.site_mobile_version_check'), {:mobile => 1}, class: "btn btn-sm btn-info" %> | | | |
          <%= link_to (t 'admin.new_blog'), new_blog_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'Sign out'), signout_path, method: "delete", class: "btn btn-sm btn-danger" %> |
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    All rights reserved. 2015. By <a href="http://www.proalab.nz/" target="_blank">Proalab</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<!-- <section id="navigation">
  <div id="undefined-sticky-wrapper" class="sticky-wrapper" style="height: 50px;"><div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div><!--/.container -->
 <!--  </div></div>
</section>navigation section end here -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta content="<%= I18n.t 'content.tags'[0..244] %>" name="keywords" />
    <meta name="author" content="Olga Yaroshenko" />

     <!-- Fonts awsome -->   
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Theme scripts -->
    <style type="text/css">.gm-style .gm-style-mtc label,.gm-style .gm-style-mtc div{font-weight:400}</style><style type="text/css">.gm-style .gm-style-cc span,.gm-style .gm-style-cc a,.gm-style .gm-style-mtc div{font-size:10px}</style><link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"><style type="text/css">@media print {  .gm-style .gmnoprint, .gmnoprint {    display:none  }}@media screen {  .gm-style .gmnoscreen, .gmnoscreen {    display:none  }}</style><style type="text/css">.gm-style{font-family:Roboto,Arial,sans-serif;font-size:11px;font-weight:400;text-decoration:none}</style>
    <!--flex slider css-->
    <link href="stylesheets/flexslider.css" rel="stylesheet">
    <!--google web fonts css-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800" rel="stylesheet" type="text/css">
    <!--animated css-->
    <link href="stylesheets/animate.css" rel="stylesheet">
    <!--owl carousel css-->
    <link href="stylesheets/owl.carousel.css" rel="stylesheet" type="text/css" media="screen">
    <link href="stylesheets/owl.theme.css" rel="stylesheet" type="text/css" media="screen">
    <!-- Theme scripts -->


    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'u.png' %>
    <!--Google Analytics-->

    <!--Google Analytics-->
    <%= yield(:head) %>
  </head>
  <body data-spy="scroll" data-target="#navigation" data-offset="80">
  <%= content = yield %>
  <!-- Words -->
  <% if current_user.try(:admin?) %>
      <%= render 'layouts/admin' %>
  <% end %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>

  <!-- Код тега ремаркетинга Google -->

  <!-- Код тега ремаркетинга Google -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_contacts.html.erb
<section id="contact" class="padding-80">
  <div class="contact-sec-1">
    <div class="container">
      <div class="section-heading text-center">
        <br> 
        <h4 class="small section-title"><span><%= t ('contact.say_hello')%>  </span></h4>
        <h2 class="large section-title"><%= t ('contact.contact')%></h2>
      </div><!--section heading-->
    </div><!--.container-->
    <div class="container">
      <div class="row">
        <div class="col-md-4" align="center">
          <a href="http://www.facebook.com/Ukraine.NewZealand" target="_blank"><i class="fa fa-facebook-square iconblack fa-5x"></i></a></br><%= t ('contact.get_social')%>
        </div>
        <div class="col-md-4" align="center">
          <a href="mailto:info@nzukrainians.org"><i class="fa fa-envelope-o iconblack fa-5x"></i></a></br><%= t ('contact.email')%>
        </div>
        <div class="col-md-4" align="center">
          <a href="skype:+6498873232?call"><i class="fa fa-phone-square iconblack fa-5x"></i></a></br><%= t ('contact.phone')%>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br> 
    <br> 
  </div><!--Contact-sec-1 end-->
</section><!--contact section end-->

<section id="home2" data-stellar-background-ratio="0.5" style="background-position: 50% 200px;">
</section>

app/views/static_pages/_main.html.erb
<section id="home" data-stellar-background-ratio="0.5" style="background-position: 50% 0px;">
  <div class="parallax-overlay"></div>
  <div class="home-content text-center">
    <div class="container">
      <h1 class=" slide-logo"><%= t ('main.name')%></h1>
      <div class="main-flex-slider">
        <ul class="slides">
          <li class="" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
            <h1><%= t ('main.head_1')%></h1>
          </li>
          <li class="" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
            <h1><%= t ('main.head_2')%></h1>
          </li>
          <li class="flex-active-slide" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 1; display: block; z-index: 2;">
            <h1><%= t ('main.head_3')%></h1>
          </li>
        </ul>
      </div>
      <h2 class="slide-btm-text"><%= t ('main.b_head')%></h2>
      <div class="home-arrow-down text-center">
        <p><a href="#contact" class="fa fa-angle-double-down fa-5x highlight"></a></p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<%= render 'static_pages/main' %>
<%= render 'layouts/header' %>
<div class="hidBlock"></div>

<!--Contact us-->
<%= render 'static_pages/contacts' %>

<!--script files-->
<!-- <script src="assets/jquery.min.js" type="text/javascript"></script> -->
<!-- <script src="assets/jquery.easing.1.3.min.js" type="text/javascript"></script> -->
<script src="assets/bootstrap.min.js" type="text/javascript"></script>
<script src="assets/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="assets/jquery.sticky.js" type="text/javascript"></script>
<script src="assets/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="assets/jquery.stellar.min.js" type="text/javascript"></script>
<!--new version v1.1 plugins-->
<script src="assets/owl.carousel.min.js" type="text/javascript"></script>
<script src="assets/jquery.nicescroll.min.js" type="text/javascript"></script>
<script src="assets/jquery.counterup.min.js" type="text/javascript"></script>
<script src="assets/custom.js" type="text/javascript"></script><div id="ascrail2000" class="nicescroll-rails" style="width: 7px; z-index: 9999999; cursor: default; position: fixed; top: 0px; height: 100%; right: 0px; opacity: 1;"><div style="position: relative; top: 0px; float: right; width: 7px; height: 58px; border: 0px; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-color: transparent; background-clip: padding-box;"></div></div>
<script type="text/javascript">
$(function() {
  $('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
</script>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>
    </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h3><p class="text-center"><%= (t 'user.all_users')%></p></h3>
<% if current_user.try(:admin?) %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">

    <table class="table table-bordered">
      <thead>
      <tr>
        <th><%= (t 'user.name') %></th>
        <th><%= (t 'user.e-mail') %></th>
        <th><%= (t 'user.created_at') %></th>
        <th><%= (t 'user.role') %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <%= will_paginate %>

      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <td>
              <% if user.admin? %>
                  <%= "Adminisrator" %>
              <% else %>
                  <%= "-" %>
              <% end %></td>
            <td><%= link_to (I18n.t 'button.show'), user, class: "btn btn-sm btn-primary" %></td>
            <td><%= link_to (I18n.t 'button.edit'), edit_user_path(user), class: "btn btn-sm btn-warning" %></td>
            <td><%= link_to (I18n.t 'button.delete'), user, method: :delete,
                            data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" %></td>
          </tr>
      <% end %>

      </tbody>
    </table>
        </div>
      </div>
    </div>
<% else %>
<% end %>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
    </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>

    </section>
  </aside>
  <div class="span8">

  </div>
</div>
    </div>